spring:
  application:
    name: coordinator
  datasource:
    url: jdbc:h2:mem:coordinator
    driver-class-name: org.h2.Driver
    username: test
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      sql-logging:
        mode: formatted
        format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      data-locations: classpath:sql/data.sql